### ISSUE TITLE
postgres:16 ls: cannot access '/docker-entrypoint-initdb.d/': Operation not permitted

### ISSUE THREAD

**Issue by ygqygq2** [docker-library/official-images#15480]
```
ls: cannot access '/docker-entrypoint-initdb.d/': Operation not permitted
ls: cannot access '/docker-entrypoint-initdb.d/': Operation not permitted
```

My docker-compose yml:

```
  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_PASSWORD: PassWord
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
```
