### ISSUE TITLE
Update official Redmine image to support Docker networking

### ISSUE THREAD

**Issue by rdgoite** [docker-library/official-images#1610]
I'm trying to define a Docker Compose mark up that allows me to start and stop Redmine and its database but it doesn't work because no matter how I try to define link from Redmine to the database, it still falls back on sqlite3 database.

**Comment by stefan-hausmann** [comment]
you also have to manually set the required environment variables (notice the subtle differences to the variable names set on the database container), as the redmine image uses these to detect if there is a linked database container, and they aren't set anymore by docker if you link the containers together.

e.g. for using mysql database container use
```
redmine:
    image: redmine
    links:
      - db:mysql
    environment:
      - MYSQL_PORT_3306_TCP=3306
      - MYSQL_ENV_MYSQL_ROOT_PASSWORD=secret
      - MYSQL_ENV_MYSQL_DATABASE=redmine
      - MYSQL_ENV_MYSQL_USER=redmine
      - MYSQL_ENV_MYSQL_PASSWORD=secret

db:
    image: mysql
    environment:      
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=redmine
      - MYSQL_USER=redmine
      - MYSQL_PASSWORD=secret
```
