### ISSUE TITLE
problem of curl registry/v2/_catalog?n=1000

### ISSUE THREAD

**Issue by cherry4477** [docker-library/official-images#1945]
there is a 504 error when curl registry/v2/_catalog?n=1000 and the reponse time is up to 2 mins.

here is the configuration of registry:

```
version: 0.1
log:
  level: info
  fields:
    service: registry

storage:
  s3:
    accesskey: 111
    secretkey: 111
    region: cn-north-1
    bucket: registry3
    encrypt: false
    secure: true
    v4auth: true
    rootdirectory: /

notifications:
  endpoints:
    - name: "portus"
      url: http://ui/service/notifications
      headers: null
      timeout: 5s
      threshold: 5
      backoff: 1s
      disabled: false

auth:
  token:
    issuer: registry-token-issuer
    realm: http://registry.dataos.io/service/token
    rootcertbundle: /etc/registry/root.crt
    service: token-service  

http:
  addr: :5000
  secret: 
```

 the error log is:

```
HTTP/1.0 504 Gateway Time-out
Cache-Control: no-cache
Connection: close
Content-Type: text/html

<html><body><h1>504 Gateway Time-out</h1>
The server didn't respond in time.
</body></html>
```
