### ISSUE TITLE
latest image does not work

### ISSUE THREAD

**Issue by Diddlik** [docker-library/official-images#9579]
I updated today to the latest image and not it stocks on creating an container.

docker-compose.yaml:

```
version: "3"
services:
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mqtt
    ports:
      - 1883:1883
    volumes:
      - ./data:/mosquitto/data
      - ./logs:/mosquitto/logs
      - ./conf/mosquitto.conf:/mosquitto/config/mosquitto.conf
    restart: always
    network_mode: "bridge"`
```
and if I try do start it: **docker-compose up**

it stay on this point:

```
Recreating mqtt ... done
Attaching to mqtt

```

I tried to delete all files, nothing helps.
